### ISSUE TITLE
Uninterruptible spin somewhere in flow-control.

### ISSUE THREAD

**Issue by TravisWhitaker** [lucasdicioccio/http2-client-grpc#13]
I encountered this issue with a simple GRPC client that just periodically sends a small message. The first few hundred messages would get through, but eventually the program would lock up and no further messages would be sent. I suspected trouble with WINDOW_UPDATE frames, but was able to confirm that the GRPC server was sending reasonable WINDOW_UPDATE frames with Wireshark.

The program consumes an entire CPU core when locked up, and the issue is ameliorated by running with `+RTS -Na` with `a > 3`. Somewhere in `http2-client-grpc` or `http2-client` there are threads spinning in an uninterruptible way (e.g. a tight loop with no allocations), starving whatever thread does the work necessary to unblock requests waiting for credit. The fix should be pretty easy: adding a `yield` to each iteration of the busy loop. @lucasdicioccio do you have any ideas off the top of your head as to where the offending loop might be?

Thanks for writing this library! Awake's grpc-haskell library has been stuck on version 1.2.0 of the C implementation and unfortunately no one (myself included) has had the time up update it. This excellent package frees me from ancient Google C code.

**Comment by TravisWhitaker** [comment]
The character of this bug is actually different than I thought.

The issue is in http2-client, PR here https://github.com/lucasdicioccio/http2-client/pull/68

**Comment by lucasdicioccio** [comment]
Thanks for the nice words, Travis!
Even if you don't have much time to help with code, bug reports like these are useful. Similarly, if you are annoyed by something in the design, let me know. In particular, I'm looking for feedback around error-handling and how we can build a good http2-client (and satellite libraries) experience for Haskellers.
