### ISSUE TITLE
Nicer handling for gRPC status codes.

### ISSUE THREAD

**Issue by TravisWhitaker** [lucasdicioccio/http2-client-grpc#16]
As the API currently exists, the caller has to interpret [gRPC status codes](https://github.com/grpc/grpc/blob/master/doc/statuscodes.md) on their own from the HTTP2 headers. A higher-level type than `RawReply` should handle these.

I've got an implementation of this in an internal library; this is a reminder for me to move it here to see what others think.

**Comment by lucasdicioccio** [comment]
Good idea! let's see if we can onboard you on https://github.com/haskell-grpc-native ;) . I see @ethercrow is also interested.

**Comment by lucasdicioccio** [comment]
Now existing at https://github.com/haskell-grpc-native/http2-grpc-haskell/issues/6 .

**Comment by TravisWhitaker** [comment]
@lucasdicioccio I'd be interested in helping out with the library any way I can!
